# Generated by Django 3.1.4 on 2021-04-18 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='replay',
            name='status',
            field=models.CharField(choices=[('WT', 'wait'), ('CF', 'confirmed'), ('RJ', 'rejected')], default='WT', max_length=2),
        ),
    ]
