# Generated by Django 3.1.4 on 2021-02-04 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postcategory',
            old_name='to_category',
            new_name='to_categorys',
        ),
        migrations.RenameField(
            model_name='postcategory',
            old_name='to_post',
            new_name='to_posts',
        ),
    ]
